### ISSUE TITLE
Error: Failed to launch the browser proces

### ISSUE THREAD

**Issue by araujo-mateus** [gyulamester/whmcstraccarzap#2]
Olá, to tendo esse erro ao usar a API do whatsapp:

root@vps-api-wpp:/www/wwwroot/API/gyulamester/whmcstraccarzap# node index.js
/www/wwwroot/API/gyulamester/whmcstraccarzap/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
            reject(new Error([
                   ^

Error: Failed to launch the browser process!
[1120/145520.712611:ERROR:command_line_handler.cc(137)] Could not create directory /www/wwwroot/API/gyulamester/whmcstraccarzap/.wwebjs_auth/session: Permission denied (13)

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/www/wwwroot/API/gyulamester/whmcstraccarzap/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/www/wwwroot/API/gyulamester/whmcstraccarzap/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (node:events:526:35)
    at Interface.close (node:internal/readline/interface:533:10)
    at Socket.onend (node:internal/readline/interface:259:10)
    at Socket.emit (node:events:526:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v18.17.1

**Comment by araujo-mateus** [comment]
Resolvido, bastou eu mudar o folder para home e atualizar permissões
